# Copyright 2026 The ChromiumOS Authors
# Distributed under the terms of the Apache License v2.

EAPI="7"

DESCRIPTION="LGPL UniKey Vietnamese engine source shipped to discharge LGPLv2 §6"
HOMEPAGE="https://github.com/fcitx/fcitx5-unikey"
# The engine source is vendored into the Chrome tree at third_party/unikey and
# statically linked into ash-chrome. This package ships that exact source (plus
# our clean-room shim and modifications) onto the image so the LGPL "source
# availability" and "ability to relink" obligations are met. The snapshot is a
# pinned tarball regenerated by files/regen-snapshot.sh from the Chrome tree.
SRC_URI=""

LICENSE="LGPL-2+"
SLOT="0"
KEYWORDS="*"
IUSE=""

# No upstream fetch: the source snapshot ships in FILESDIR.
S="${WORKDIR}/unikey"

src_unpack() {
	mkdir -p "${S}" || die
	tar xzf "${FILESDIR}/unikey-engine-src-${PV}.tar.gz" -C "${S}" ||
		die "failed to unpack the vendored UniKey engine source snapshot"
}

src_install() {
	# Ship the complete engine source (engine core + clean-room charset/table
	# shim + our BUILD.gn and modifications) alongside the binary. ash-chrome
	# links this LGPL engine statically; per LGPLv2 §6 we make the modified
	# engine source available and provide the means to relink -- see the
	# RELINK.README installed next to it. The image is BSD-3/Chromium licensed;
	# only this replaceable component carries the LGPL obligation.
	insinto /usr/share/unikey-engine-source
	doins -r "${S}"/*
	doins "${FILESDIR}/RELINK.README"

	# Also expose the license text where the licensing tooling looks.
	insinto /usr/share/licenses/unikey-engine
	newins "${S}/LICENSE" LICENSE
}
